name = "barryliu-github-io"
compatibility_date = "2026-05-18"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "POST_STATS"
id = "81842e7005854e9a928d69b16f8ebd30"
preview_id = "7c7460a5ae4b4feeb43b9f9f6d255e6b"
