name = "barryliu-github-io"
compatibility_date = "2026-05-18"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "POST_STATS"
id = "local_post_stats"
preview_id = "local_post_stats_preview"
